[tools]
"node" = "latest"
"npm:copilot-api" = "latest"

[env]
ANTHROPIC_BASE_URL = "http://localhost:4141"
ANTHROPIC_AUTH_TOKEN = "sk-dummy"
ANTHROPIC_MODEL = "claude-sonnet-4.5"
ANTHROPIC_DEFAULT_HAIKU_MODEL = "gpt-5-mini"
DISABLE_NON_ESSENTIAL_MODEL_CALLS = "1"
CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = "1"

[tasks.inspect]
run = "npx @modelcontextprotocol/inspector --transport http --url http://localhost:8000/mcp"

[tasks.run_server]
run = "uv run mcp_server/server.py"

[tasks.run_client]
run = "uv run mcp_client/client.py"
